// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jRmbiwPUEMmOT_j9Hw_aVfgzLTFyrm4',
    appId: '1:441774323742:web:064b9c0e23b996112bd60f',
    messagingSenderId: '441774323742',
    projectId: 'flutter-demo-807fd',
    authDomain: 'flutter-demo-807fd.firebaseapp.com',
    storageBucket: 'flutter-demo-807fd.appspot.com',
    measurementId: 'G-H376HL56FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6c4KSTJ10O3yzP8JUAaDMSyqopGDSIg',
    appId: '1:441774323742:android:2ed701c4b5a25ca32bd60f',
    messagingSenderId: '441774323742',
    projectId: 'flutter-demo-807fd',
    storageBucket: 'flutter-demo-807fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX8CiNe4ouY9w0EZYhvBRaGS9s1n_-vok',
    appId: '1:441774323742:ios:eff122e7f4a9a1dc2bd60f',
    messagingSenderId: '441774323742',
    projectId: 'flutter-demo-807fd',
    storageBucket: 'flutter-demo-807fd.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
